CREATE TABLE SESSAO (

	ID INT PRIMARY KEY,
	Nome VARCHAR(150),
	Descricao VARCHAR(250),
	Tipo char(1),
	Opcao1 VARCHAR(3),
	Opcao2 VARCHAR(3),
	Participacao VARCHAR(1),
	Data_Inicial VARCHAR(10),
	Data_Final VARCHAR(10),
	Controle VARCHAR(1),
	Qtd_Max INT,
	Qtd_VotosPos INT,
	Qtd_VotosNeg INT,
	Estado VARCHAR(2)
)

CREATE TABLE Voto (
		
	Resposta INT,
	Estado VARCHAR(2)
	
)

ALTER TABLE Voto
ADD COLUMN ID INT;

ALTER TABLE Voto
ADD CONSTRAINT FK_SESSAO FOREIGN KEY (ID) REFERENCES Sessao(ID);

ALTER TABLE Voto
ALTER COLUMN resposta TYPE VARCHAR(3)




